-- Exceção de Valor da venda zerado
CREATE EXCEPTION EXCECAO_VALOR_VENDA_ZERADO 'O valor da venda não pode ser zero';

CREATE OR ALTER TRIGGER TRG_VALOR_VENDA
FOR VENDA BEFORE INSERT
AS
BEGIN
    IF (new.VALOR_TOTAL = 0) THEN
        EXCEPTION EXCECAO_VALOR_VENDA_ZERADO;
 
END

--Exceção de valor nulo no medicamento
CREATE EXCEPTION EXCECAO_VALOR_NULO 'Valor Nulo Não Permitido';

CREATE OR ALTER TRIGGER TRG_VALOR_NULO_MEDICAMENTO
FOR MEDICAMENTO BEFORE INSERT
AS
BEGIN
    IF (new.NOME IS NULL OR new.ID_TIPO_MEDICAMENTO IS NULL) THEN
        EXCEPTION EXCECAO_VALOR_NULO;
   
END



