-- INSERIR - Medicamento:

CREATE OR ALTER PROCEDURE NOVO_MEDICAMENTO
(PID_MEDICAMENTO INTEGER, PNOME VARCHAR(40), PID_TIPO_MEDICAMENTO INTEGER)
AS
BEGIN
    INSERT INTO MEDICAMENTO VALUES (:PID_MEDICAMENTO, :PNOME, :PID_TIPO_MEDICAMENTO);
END

-- ATUALIZAÇÃO - Medicamento:

CREATE OR ALTER PROCEDURE ATUALIZAR_MEDICAMENTO
(PID_MEDICAMENTO INTEGER, PNOME VARCHAR(40), PID_TIPO_MEDICAMENTO INTEGER)
AS
BEGIN
    UPDATE MEDICAMENTO SET NOME=:PNOME, ID_TIPO_MEDICAMENTO=:PID_TIPO_MEDICAMENTO
    WHERE ID_MEDICAMENTO=:PID_MEDICAMENTO;
END

-- SELECIONE - Medicamento:

CREATE OR ALTER PROCEDURE VERIFICAR_MEDICAMENTO
(PID_MEDICAMENTO INTEGER)
RETURNS
    (ID_MEDICAMENTO INTEGER, NOME VARCHAR(40), ID_TIPO_MEDICAMENTO INTEGER)
AS
BEGIN
    FOR
        SELECT ID_MEDICAMENTO, NOME, ID_TIPO_MEDICAMENTO
        FROM MEDICAMENTO
        WHERE ID_MEDICAMENTO = :PID_MEDICAMENTO
        INTO :ID_MEDICAMENTO, :NOME, :ID_TIPO_MEDICAMENTO
    DO
    SUSPEND;
END

-- EXCLUIR - Medicamento:

CREATE OR ALTER PROCEDURE APAGAR_MEDICAMENTO
(PID_MEDICAMENTO INTEGER)
AS
BEGIN
    DELETE FROM MEDICAMENTO WHERE ID_MEDICAMENTO=:PID_MEDICAMENTO;
END

-- INSERIR - Cliente:

CREATE OR ALTER PROCEDURE NOVO_CLIENTE
(PID_CLIENTE INTEGER, PNOME VARCHAR(40), PENDERECO VARCHAR(40), PCIDADE VARCHAR(30), PUF VARCHAR(2), PTELEFONE VARCHAR(20), PCONTATO VARCHAR(20))
AS
BEGIN
    INSERT INTO CLIENTE (ID_CLIENTE, NOME, ENDERECO, CIDADE, UF)
    VALUES (:PID_CLIENTE, :PNOME, :PENDERECO, :PCIDADE, :PUF);
END

-- ATUALIZAÇÃO - Cliente:

CREATE OR ALTER PROCEDURE ATUALIZAR_CLIENTE
(PID_CLIENTE INTEGER, PNOME VARCHAR(40), PENDERECO VARCHAR(40), PCIDADE VARCHAR(30), PUF VARCHAR(2))
AS
BEGIN
    UPDATE CLIENTE SET NOME = :PNOME, ENDERECO = :PENDERECO, CIDADE = :PCIDADE, UF = :PUF
    WHERE ID_CLIENTE = :PID_CLIENTE;
END


-- SELECIONE - Cliente:

CREATE OR ALTER PROCEDURE VERIFICAR_CLIENTE
(PID_CLIENTE INTEGER)
RETURNS (ID_CLIENTE INTEGER, NOME VARCHAR(40), ENDERECO VARCHAR(40), CIDADE VARCHAR(30), UF VARCHAR(2))
AS
BEGIN
    FOR
        SELECT ID_CLIENTE, NOME, ENDERECO, CIDADE, UF
        FROM CLIENTE
        WHERE ID_CLIENTE=:PID_CLIENTE
        INTO :ID_CLIENTE, :NOME, :ENDERECO, :CIDADE, :UF
    DO
    SUSPEND;
END

-- EXCLUIR - Cliente:

CREATE OR ALTER PROCEDURE APAGAR_CLIENTE
(PID_CLIENTE INTEGER)
AS
BEGIN
    DELETE FROM CLIENTE WHERE ID_CLIENTE=:PID_CLIENTE;
END

