 -- Gatilho Delete Cliente                                                                                                            -- Gatilho Delete Cliente

CREATE OR ALTER TRIGGER LOG_DELETE_CLIENTE FOR CLIENTE
ACTIVE BEFORE DELETE
AS
BEGIN
    INSERT INTO LOG_DELETE_CLIENTE (ID_CLIENTE, NOME, DATA_ACAO)
    SELECT OLD.ID_CLIENTE, OLD.NOME, CURRENT_TIMESTAMP
    FROM Cliente;
END

-- Gatilho Update Preco

CREATE OR ALTER TRIGGER LOG_UPDATE_PRECO FOR 
MEDICAMENTO
ACTIVE BEFORE UPDATE
AS
BEGIN
    INSERT INTO LOG_UPDATE_PRECO (ID_MEDICAMENTO, PRECO_ANTIGO, PRECO_NOVO, DATA_ACAO)
    SELECT NEW.ID_MEDICAMENTO, OLD.PRECO, NEW.PRECO, CURRENT_TIMESTAMP
    FROM MEDICAMENTO;
END   

-- Gatilho Insert Fornecedor

CREATE OR ALTER TRIGGER LOG_INSERT_FORNECEDOR FOR FORNECEDOR
ACTIVE AFTER INSERT
AS
BEGIN
    INSERT INTO LOG_INSERT_FORNECEDOR (ID_FORNECEDOR, NOME, DATA_ACAO)
    SELECT NEW.ID_FORNECEDOR, NEW.NOME, CURRENT_TIMESTAMP
    FROM FORNECEDOR;
END

--GERADORES E GATILHOS
--Não usamos no banco, só depois de já ter inseridos os dados com suas IDs.

--Gerador de todas as tabelas

CREATE GENERATOR GEN_ID_CLIENTE;
CREATE GENERATOR GEN_ID_VENDA;
CREATE GENERATOR GEN_ID_MEDICAMENTO;
CREATE GENERATOR GEN_ID_FORNECEDOR;
CREATE GENERATOR GEN_ID_VENDEDOR;
CREATE GENERATOR GEN_ID_FORMA_PAGAMENTO;
CREATE GENERATOR GEN_ID_TIPO_MEDICAMENTO;
CREATE GENERATOR GEN_ID_VENDA_MEDICAMENTO;

-- Gatilhos de todos os geradores
-- CLIENTE
CREATE OR ALTER TRIGGER SET_ID_CLIENTE
FOR CLIENTE BEFORE INSERT
AS
BEGIN
    new.ID_CLIENTE = GEN_ID(GEN_ID_CLIENTE, 1);
END

-- VENDA
CREATE OR ALTER TRIGGER SET_ID_VENDA
FOR VENDA BEFORE INSERT
AS
BEGIN
    new.ID_VENDA = GEN_ID(GEN_ID_VENDA, 1);
END

-- MEDICAMENTO
CREATE OR ALTER TRIGGER SET_ID_MEDICAMENTO
FOR MEDICAMENTO BEFORE INSERT
AS
BEGIN
    new.ID_MEDICAMENTO = GEN_ID(GEN_ID_MEDICAMENTO, 1);
END

-- FORNECEDOR
CREATE OR ALTER TRIGGER SET_ID_FORNECEDOR
FOR FORNECEDOR BEFORE INSERT
AS
BEGIN
    new.ID_FORNECEDOR = GEN_ID(GEN_ID_FORNECEDOR, 1);
END

-- VENDEDOR
CREATE OR ALTER TRIGGER SET_ID_VENDEDOR
FOR VENDEDOR BEFORE insert
AS
BEGIN
new.ID_VENDEDOR = GEN_ID(GEN_ID_VENDEDOR, 1);
end

-- FORMA DE PAGAMENTO
CREATE OR ALTER TRIGGER SET_ID_FORMA_PAGAMENTO
FOR FORMA_PAGAMENTO BEFORE INSERT
AS
BEGIN
    new.ID_FORMA_PAGAMENTO = GEN_ID(GEN_ID_FORMA_PAGAMENTO, 1);
END

-- TIPO MEDICAMENTO
CREATE OR ALTER TRIGGER SET_ID_TIPO_MEDICAMENTO
FOR TIPO_MEDICAMENTO BEFORE INSERT
AS
BEGIN
    new.ID_TIPO_MEDICAMENTO = GEN_ID(GEN_ID_TIPO_MEDICAMENTO, 1);
END

-- VENDA MEDICAMENTO
CREATE OR ALTER TRIGGER SET_ID_VENDA_MEDICAMENTO
FOR VENDA_MEDICAMENTO BEFORE INSERT
AS
BEGIN
    new.ID_VENDA_MEDICAMENTO = GEN_ID(GEN_ID_VENDA_MEDICAMENTO, 1);
END
